interface TermsLimitationOfLiabilityProps { companyName: string }

/** Terms section: Limitation of Liability */
export function TermsLimitationOfLiability({ companyName }: TermsLimitationOfLiabilityProps) {
  return (
    <>
<h4>Limitation of Liability</h4>
      <p className="uppercase">
        IN NO EVENT WILL {companyName}, ITS SUBSIDIARIES, AFFILIATES, OFFICERS,
        DIRECTORS, EMPLOYEES, REPRESENTATIVES, AGENTS, PARTNERS, AND LICENSORS
        BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT
        OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE SERVICES OR
        ANY CONTENT ASSOCIATED WITH THE SERVICES, OR SUCH OTHER SITES OR ANY
        SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES, INCLUDING ANY DIRECT,
        INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
        INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING,
        EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS
        OR ANTICIPATED SAVINGS, LOSS OF BUSINESS OPPORTUNITY, BUSINESS
        INTERRUPTION, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER
        CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE,
        EVEN IF FORESEEABLE. THESE EXCLUSIONS OR LIMITATIONS WILL APPLY
        REGARDLESS OF WHETHER OR NOT {companyName} HAS BEEN WARNED OF THE
        POSSIBILITY OF SUCH DAMAGES.
      </p>
      <p className="uppercase">
        THE FOREGOING DOES NOT AFFECT ANY LIABILITY WHICH CANNOT BE EXCLUDED OR
        LIMITED UNDER APPLICABLE LAW. TO THE EXTENT LIABILITY CANNOT BE EXCLUDED
        OR LIMITED AS SET FORTH ABOVE, IN NO EVENT SHALL {companyName} BE LIABLE
        FOR ANY CLAIM, WHETHER IN CONTRACT, TORT, OR UNDER ANY OTHER THEORY OF
        LIABILITY, IN EXCESS OF $100.
      </p>
    </>
  );
}
