interface TermsWarrantyDisclaimerProps { companyName: string }

/** Terms section: Warranty Disclaimer */
export function TermsWarrantyDisclaimer({ companyName }: TermsWarrantyDisclaimerProps) {
  return (
    <>
<h4>Warranty Disclaimer</h4>
      <p className="uppercase">
        THE SERVICES ARE PROVIDED TO YOU “AS IS WITH ALL FAULTS” AND “AS
        AVAILABLE” WITHOUT WARRANTY OF ANY KIND, AND {companyName} AND ITS
        SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES,
        REPRESENTATIVES, AGENTS, PARTNERS, AND LICENSORS HEREBY DISCLAIM ALL
        WARRANTIES AND CONDITIONS WITH RESPECT TO THE SERVICES WHETHER EXPRESS
        OR IMPLIED AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE,
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY,
        AND NON-INFRINGEMENT. {companyName} DOES NOT WARRANT AGAINST
        INTERFERENCE WITH YOUR ENJOYMENT OF THE SERVICES, THE AVAILABILITY OF
        CONTENT, THAT THE FUNCTIONS CONTAINED IN THE SERVICES WILL MEET YOUR
        REQUIREMENTS, THAT THE SERVICES WILL BE FREE OF VIRUSES OR OTHER HARMFUL
        COMPONENTS, THAT THE OPERATION OF THE SERVICES WILL BE UNINTERRUPTED OR
        ERROR-FREE, THAT DEFECTS IN THE SERVICES WILL BE CORRECTED, OR THAT THE
        FUNCTIONS CONTAINED IN THE SERVICES WILL FUNCTION WITH OTHER MOBILE APPS
        OR HARDWARE, OR WITHIN A SYSTEM. NO ORAL OR WRITTEN INFORMATION OR
        ADVICE GIVEN BY {companyName} OR AN {companyName} AUTHORIZED
        REPRESENTATIVE SHALL CREATE A WARRANTY. SOME JURISDICTIONS DO NOT ALLOW
        THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE
        STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION MAY NOT APPLY.
      </p>
    </>
  );
}
